name: CI

# Triggers the workflow on all pushes.
on: push

jobs:
  test:
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    runs-on: "ubuntu-20.04"
    strategy:
      matrix:
        include:
          - pair:
              elixir: "1.13.4"
              otp: "24.x"
          - pair:
              elixir: "1.14.5"
              otp: "25.x"
          - pair:
              elixir: "1.15.7"
              otp: "26.x"

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Setup Elixir / Erlang"
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.pair.otp}}
          elixir-version: ${{matrix.pair.elixir}}

      - name: "Get the deps"
        run: mix deps.get

      - name: "Run the tests"
        run: mix test
